=== FotecGmbH/FOTEC-LENIE/src/bs.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="SetCsSetting" nillable="true" type="SetCsSetting" />
	<xs:complexType name="SetCsSetting">
		<xs:attribute name="FileName" type="xs:string" />
		<xs:attribute name="ForCsSettings" type="EnumCsSettings" use="required" />
		<xs:attribute name="Usings">
			<xs:simpleType>
				<xs:list itemType="xs:string" />
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Interfaces">
			<xs:simpleType>
				<xs:list itemType="xs:string" />
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="EnumCsSettings">
		<xs:restriction base="xs:string">
			<xs:enumeration value="None" />
			<xs:enumeration value="Exchange" />
			<xs:enumeration value="WebExchange" />
			<xs:enumeration value="CommonAppSettings" />
			<xs:enumeration value="File1" />
			<xs:enumeration value="File2" />
			<xs:enumeration value="File3" />
			<xs:enumeration value="File4" />
			<xs:enumeration value="File5" />
			<xs:enumeration value="File6" />
			<xs:enumeration value="File7" />
			<xs:enumeration value="File8" />
			<xs:enumeration value="File9" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="SetProject" nillable="true" type="SetProject" />
	<xs:complexType name="SetProject">
		<xs:attribute name="RootFolder" type="xs:string" />
		<xs:attribute default="None" name="CsSettings" type="EnumCsSettings" />
		<xs:attribute default="None" name="CommonFile" type="EnumCommonFiles" />
	</xs:complexType>
	<xs:simpleType name="EnumCommonFiles">
		<xs:restriction base="xs:string">
			<xs:enumeration value="None" />
			<xs:enumeration value="LaunchConnectivityHost" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="SetProp" nillable="true" type="SetProp" />
	<xs:complexType name="SetProp">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="Targets" type="ArrayOfSetTarget" />
			<xs:element minOccurs="0" maxOccurs="1" name="BranchValues" type="ArrayOfSetBranchValue" />
		</xs:sequence>
		<xs:attribute default="Common" name="PropType" type="EnumPropType" />
		<xs:attribute default="false" name="IsSecureProperty" type="xs:boolean" />
		<xs:attribute default="false" name="IsRequiredValue" type="xs:boolean" />
		<xs:attribute name="Description" type="xs:string" />
		<xs:attribute name="DefaultValue" type="xs:string" />
		<xs:attribute default="InvariantCulture" name="ValueComparison" type="StringComparison" />
	</xs:complexType>
	<xs:complexType name="ArrayOfSetTarget">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SetTarget" nillable="true" type="SetTarget" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SetTarget">
		<xs:attribute name="TargetType" type="EnumSetTargetTypes" use="required" />
		<xs:attribute name="Destinations">
			<xs:simpleType>
				<xs:list itemType="xs:string" />
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute default="" name="OnlyForProject" type="xs:string" />
		<xs:attribute default="None" name="CsSettings" type="EnumCsSettings" />
	</xs:complexType>
	<xs:simpleType name="EnumSetTargetTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CsProj" />
			<xs:enumeration value="AssemblyInfo" />
			<xs:enumeration value="Nuspec" />
			<xs:enumeration value="AndroidManifest" />
			<xs:enumeration value="InfoPlist" />
			<xs:enumeration value="EntitlementsPlist" />
			<xs:enumeration value="CsSetting" />
			<xs:enumeration value="CommonFile" />
			<xs:enumeration value="LaunchSettings" />
			<xs:enumeration value="IndexHtml" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ArrayOfSetBranchValue">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SetBranchValue" nillable="true" type="SetBranchValue" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SetBranchValue">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="LocalOverrides" type="ArrayOfSetLocalOverride" />
		</xs:sequence>
		<xs:attribute name="BranchName" type="xs:string" />
		<xs:attribute name="Value" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="ArrayOfSetLocalOverride">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SetLocalOverride" nillable="true" type="SetLocalOverride" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SetLocalOverride">
		<xs:attribute name="HostName" type="xs:string" />
		<xs:attribute default="" name="NetworkName" type="xs:string" />
		<xs:attribute name="Value" type="xs:string" />
	</xs:complexType>
	<xs:simpleType name="EnumPropType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Common" />
			<xs:enumeration value="Version" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StringComparison">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CurrentCulture" />
			<xs:enumeration value="CurrentCultureIgnoreCase" />
			<xs:enumeration value="InvariantCulture" />
			<xs:enumeration value="InvariantCultureIgnoreCase" />
			<xs:enumeration value="Ordinal" />
			<xs:enumeration value="OrdinalIgnoreCase" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="SetBranchValue" nillable="true" type="SetBranchValue" />
	<xs:element name="SetLocalOverride" nillable="true" type="SetLocalOverride" />
	<xs:element name="SetTarget" nillable="true" type="SetTarget" />
	<xs:element name="SetRoot" nillable="true" type="SetRoot" />
	<xs:complexType name="SetRoot">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="TargetDirectories" type="ArrayOfSetProject" />
			<xs:element minOccurs="0" maxOccurs="1" name="CsSettings" type="ArrayOfSetCsSetting" />
			<xs:element minOccurs="0" maxOccurs="1" name="Properties" type="ArrayOfSetProp" />
		</xs:sequence>
		<xs:attribute default="Kunde.Projekt" name="ProjectId" type="xs:string" />
		<xs:attribute name="KeyVault" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="ArrayOfSetProject">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SetProject" nillable="true" type="SetProject" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ArrayOfSetCsSetting">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SetCsSetting" nillable="true" type="SetCsSetting" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ArrayOfSetProp">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SetProp" nillable="true" type="SetProp" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="EnumCommonFiles" type="EnumCommonFiles" />
	<xs:element name="EnumCsSettings" type="EnumCsSettings" />
	<xs:element name="EnumPropType" type="EnumPropType" />
	<xs:element name="EnumSetTargetTypes" type="EnumSetTargetTypes" />
</xs:schema>

=== FotecGmbH/FOTEC-LENIE/src/bs.xml
<SetRoot ProjectId="DIHOST.Lenie" KeyVault="https://bissprodkeyvault.vault.azure.net/"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
         xsi:noNamespaceSchemaLocation="bs.xsd">
	<TargetDirectories>
		<SetProject RootFolder="BaseApp" />
		<SetProject RootFolder="BaseApp.View.Xamarin" />
		<SetProject RootFolder="WpfApp" />
		<SetProject RootFolder="AndroidApp" />
		<SetProject RootFolder="IOsApp" />
		<SetProject RootFolder="ConnectivityHost" CommonFile="LaunchConnectivityHost" />
		<SetProject RootFolder="Database" />
		<SetProject RootFolder="Exchange" CsSettings="Exchange" />
		<SetProject RootFolder="WebExchange" CsSettings="WebExchange" />
	</TargetDirectories>
	<CsSettings>
		<SetCsSetting FileName="AppSettings.cs" ForCsSettings="Exchange"
		              Usings="Exchange.Interfaces Biss.Apps.Components Biss.Apps.Connectivity.Interfaces Biss.Apps.Connectivity.Sa Biss.Apps.Enum Biss.Apps.Interfaces Biss.Apps.Model Biss.Dc.Client Biss.Apps.Map.Interface Biss.Apps.Push.Interfaces"
		              Interfaces="IAppSettings IAppSettingsNavigation IAppSettingsFiles IAppSettingConnectivity IAppSettingsPush IAppSettingsLinks IAppSettingsMap IAppSettingsAppCenter" />
		<SetCsSetting FileName="WebSettings.cs" ForCsSettings="WebExchange"
		              Usings="Biss.Apps.Service.Push WebExchange.Interfaces"
		              Interfaces="IWebSettingsAzureFiles IAppServiceSettingPush IAppSettingsDataBase IAppSettingsEMail IWebSettingsSms" />
	</CsSettings>
	<Properties>
		<SetProp Description="Produktversion" DefaultValue="1.4.1" PropType="Version" IsRequiredValue="true">
			<Targets>
				<SetTarget TargetType="CsProj" Destinations="Project/PropertyGroup/Version" />
				<SetTarget TargetType="AssemblyInfo" Destinations="AssemblyVersion AssemblyFileVersion" />
				<SetTarget TargetType="AndroidManifest" Destinations="manifest#android:versionName" />
				<SetTarget TargetType="InfoPlist" Destinations="CFBundleVersion CFBundleShortVersionString" />
				<SetTarget TargetType="CsSetting" Destinations="AppVersion" CsSettings="Exchange" />
			</Targets>
		</SetProp>

		<SetProp Description="DC Host - SignalR" DefaultValue="https://dihost-lenie-connectivityhost.azurewebsites.net">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="DcSignalHost" CsSettings="Exchange" />
				<SetTarget TargetType="CommonFile" Destinations="Host" />
				<SetTarget TargetType="LaunchSettings"
				           Destinations="iisSettings/iisExpress#applicationUrl profiles/ServerApp#applicationUrl"
				           OnlyForProject="ConnectivityHost" />
			</Targets>
			<BranchValues>
				<SetBranchValue BranchName="beta" Value="https://dihost-lenie-connectivityhost-beta.azurewebsites.net">
				</SetBranchValue>
				<SetBranchValue BranchName="dev" Value="https://dihost-lenie-connectivityhost-dev.azurewebsites.net">
					<LocalOverrides>
					</LocalOverrides>
				</SetBranchValue>
			</BranchValues>
		</SetProp>

		<SetProp Description="SA Host - REST" DefaultValue="http://dihost-lenie-connectivityhost.azurewebsites.net/api/">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="SaApiHost" CsSettings="Exchange" />
			</Targets>
			<BranchValues>
				<SetBranchValue BranchName="beta" Value="http://dihost-lenie-connectivityhost-beta.azurewebsites.net/api/">
				</SetBranchValue>
				<SetBranchValue BranchName="dev" Value="http://dihost-lenie-connectivityhost-dev.azurewebsites.net/api/">
				</SetBranchValue>
			</BranchValues>
		</SetProp>

		<SetProp Description="App Name" DefaultValue="LENIE">
			<Targets>
				<SetTarget TargetType="AndroidManifest" Destinations="manifest/application#android:label" />
				<SetTarget TargetType="InfoPlist" Destinations="CFBundleDisplayName" />
				<SetTarget TargetType="CsSetting" Destinations="AppName" CsSettings="Exchange" />
			</Targets>
			<BranchValues>
				<SetBranchValue BranchName="beta" Value="LENIE Beta" />
				<SetBranchValue BranchName="dev" Value="LENIE Dev" />
			</BranchValues>
		</SetProp>

		<SetProp Description="App Identifier" DefaultValue="at.dihost.lenie">
			<Targets>
				<SetTarget TargetType="AndroidManifest" Destinations="manifest#package" />
				<SetTarget TargetType="InfoPlist" Destinations="CFBundleIdentifier" />
				<SetTarget TargetType="CsSetting" Destinations="PackageName" CsSettings="Exchange" />
			</Targets>
			<BranchValues>
				<SetBranchValue BranchName="beta" Value="at.dihost.lenie.beta" />
				<SetBranchValue BranchName="dev" Value="at.dihost.lenie.dev" />
			</BranchValues>
		</SetProp>

		<SetProp Description="App Ordner auf Plattform" DefaultValue="Lenie">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="ProjectWorkUserFolder" CsSettings="Exchange" />
			</Targets>
			<BranchValues>
				<SetBranchValue BranchName="beta" Value="LenieBeta" />
				<SetBranchValue BranchName="dev" Value="LenieDev" />
			</BranchValues>
		</SetProp>

		<SetProp Description="Id des Notification-Channels" DefaultValue="DefaultId">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="NotificationChannelId" CsSettings="Exchange" />
			</Targets>
		</SetProp>

		<SetProp Description="Name des Notification-Channels" DefaultValue="PushBenachrichtigungen">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="NotificationChannelName" CsSettings="Exchange" />
			</Targets>
		</SetProp>

		<SetProp
			Description="Push - Firebase Project Id - &lt;inheritdoc cref=&quot;IAppServiceSettingPush.PushProjectId&quot;/&gt;"
			DefaultValue="dihost-lenie">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="PushProjectId" CsSettings="WebExchange" />
			</Targets>
		</SetProp>

		<SetProp
			Description="Push - Firebase Service Account Id - &lt;inheritdoc cref=&quot;IAppServiceSettingPush.PushServiceAccountId&quot;/&gt;"
			DefaultValue="DIHOST:LENIE:PushServiceAccountId" IsRequiredValue="true" IsSecureProperty="true">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="PushServiceAccountId" CsSettings="WebExchange" />
			</Targets>
		</SetProp>

		<SetProp
			Description="Push - Firebase Private Key Id - &lt;inheritdoc cref=&quot;IAppServiceSettingPush.PushPrivateKeyId&quot;/&gt;"
			DefaultValue="DIHOST:LENIE:PushPrivateKeyId" IsRequiredValue="true" IsSecureProperty="true">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="PushPrivateKeyId " CsSettings="WebExchange" />
			</Targets>
		</SetProp>

		<SetProp
			Description="Push - Firebase Private Key - &lt;inheritdoc cref=&quot;IAppServiceSettingPush.PushPrivateKey&quot;/&gt;"
			DefaultValue="DIHOST:LENIE:PushPrivateKey" IsRequiredValue="true" IsSecureProperty="true">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="PushPrivateKey " CsSettings="WebExchange" />
			</Targets>
		</SetProp>

		<SetProp Description="Standard Topic" DefaultValue="DEFAULT">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="DefaultTopic" CsSettings="Exchange" />
			</Targets>
		</SetProp>

		<SetProp Description="Bing Maps Key - WPF (VWT)" DefaultValue="FOTEC:BingMapsKey" IsRequiredValue="true"
		         IsSecureProperty="true">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="BingMapsKey" CsSettings="Exchange" />
			</Targets>
		</SetProp>

		<SetProp Description="Google Maps Key Android und Blazor" DefaultValue="FOTEC:GoogleMapsKey" IsRequiredValue="true"
		         IsSecureProperty="true">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="GoogleMapsKey" CsSettings="Exchange" />
				<SetTarget TargetType="AndroidManifest"
				           Destinations="manifest/application/meta-data#android:value##android:name=com.google.android.geo.API_KEY" />
				<SetTarget TargetType="IndexHtml" Destinations="GOOGLEMAPKEY" />
			</Targets>
		</SetProp>

		<SetProp Description="Datenbank" DefaultValue="lenie-db-release">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="ConnectionStringDb" CsSettings="WebExchange" />
			</Targets>
			<BranchValues>
				<SetBranchValue BranchName="beta" Value="lenie-db-beta" />
				<SetBranchValue BranchName="dev" Value="lenie-db-dev" />
			</BranchValues>
		</SetProp>

		<SetProp Description="Datenbank-Server" DefaultValue="DIHOST:LENIE:SqlServer" IsRequiredValue="true"
		         IsSecureProperty="true">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="ConnectionStringDbServer" CsSettings="WebExchange" />
			</Targets>
		</SetProp>

		<SetProp Description="Datenbank User" DefaultValue="DIHOST:LENIE:SqlServerUser" IsRequiredValue="true"
		         IsSecureProperty="true">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="ConnectionStringUser" CsSettings="WebExchange" />
			</Targets>
		</SetProp>

		<SetProp Description="Datenbank User Passwort" DefaultValue="DIHOST:LENIE:SqlServerPassword" IsRequiredValue="true"
		         IsSecureProperty="true">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="ConnectionStringUserPwd" CsSettings="WebExchange" />
			</Targets>
		</SetProp>

		<SetProp Description="Connection string für den Blob" DefaultValue="DIHOST:LENIE:BlobConString"
		         IsRequiredValue="true" IsSecureProperty="true">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="BlobConnectionString" CsSettings="WebExchange" />
			</Targets>
		</SetProp>

		<SetProp Description="Container Name im Blob" DefaultValue="lenierelease">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="BlobContainerName" CsSettings="WebExchange" />
			</Targets>
			<BranchValues>
				<SetBranchValue BranchName="beta" Value="leniebeta" />
				<SetBranchValue BranchName="dev" Value="leniedev" />
			</BranchValues>
		</SetProp>

		<SetProp Description="Cdn link oder public Bloblink für Filelink"
		         DefaultValue="https://leniestorage.blob.core.windows.net/">
			<Targets>
				<SetTarget TargetType="CsSetting" Destinations="CdnLink" CsSettings="WebExchange" />
			</Targets>
